import { Info, ChevronDown } from 'lucide-react'
import { useState } from 'react'

interface InfoTooltipProps {
  label: string
  tooltip: string
  learnMore?: string
}

export function InfoTooltip({ label, tooltip, learnMore }: InfoTooltipProps) {
  const [showTooltip, setShowTooltip] = useState(false)

  return (
    <div className="relative inline-flex items-center gap-1">
      <span className="font-medium text-sm">{label}</span>
      <div
        className="relative"
        onMouseEnter={() => setShowTooltip(true)}
        onMouseLeave={() => setShowTooltip(false)}
      >
        <button
          className="p-0.5 hover:bg-muted rounded transition-colors"
          title={tooltip}
          aria-label={`Info: ${tooltip}`}
        >
          <Info className="h-4 w-4 text-muted-foreground hover:text-foreground transition-colors" />
        </button>

        {/* Tooltip */}
        {showTooltip && (
          <div className="absolute left-0 bottom-full mb-2 w-48 bg-card border border-border rounded-lg p-2 text-xs text-muted-foreground shadow-lg z-40 before:absolute before:left-2 before:top-full before:w-2 before:h-2 before:bg-card before:border-r before:border-b before:border-border before:rotate-45">
            {tooltip}
            {learnMore && (
              <div className="mt-2 pt-2 border-t border-border text-xs text-accent">
                {learnMore}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

interface ExpandableInfoProps {
  title: string
  description: string
  children?: React.ReactNode
}

export function ExpandableInfo({ title, description, children }: ExpandableInfoProps) {
  const [isExpanded, setIsExpanded] = useState(false)

  return (
    <div className="rounded-lg border border-border overflow-hidden">
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full flex items-center justify-between p-3 hover:bg-muted/50 transition-colors"
      >
        <div className="flex items-center gap-2">
          <Info className="h-4 w-4 text-accent flex-shrink-0" />
          <span className="font-medium text-sm">{title}</span>
        </div>
        <ChevronDown
          className={`h-4 w-4 text-muted-foreground transition-transform ${
            isExpanded ? 'rotate-180' : ''
          }`}
        />
      </button>

      {isExpanded && (
        <div className="border-t border-border p-3 bg-muted/30 text-sm text-muted-foreground space-y-2">
          <p>{description}</p>
          {children}
        </div>
      )}
    </div>
  )
}

// Metric definitions library
export const METRIC_DEFINITIONS: Record<string, { name: string; definition: string; learnMore: string }> = {
  sharpe_ratio: {
    name: 'Sharpe Ratio',
    definition: 'Measures risk-adjusted returns - how much excess return you get for the risk taken',
    learnMore: 'Higher is better (>1.0 is good, >2.0 is excellent). Compares your returns to a risk-free rate.',
  },
  max_drawdown: {
    name: 'Max Drawdown',
    definition: 'The largest peak-to-trough decline in portfolio value during a period',
    learnMore: 'Represents the worst-case scenario loss from peak. Lower drawdowns indicate better risk management.',
  },
  win_rate: {
    name: 'Win Rate',
    definition: 'Percentage of profitable trades out of all trades executed',
    learnMore: 'Not the only important metric - consider average win/loss size and Sharpe ratio too.',
  },
  volatility: {
    name: 'Volatility',
    definition: 'Standard deviation of returns - measures how much your returns fluctuate',
    learnMore: 'Higher volatility means more unpredictable returns. Lower is generally preferred for stability.',
  },
  sortino_ratio: {
    name: 'Sortino Ratio',
    definition: 'Like Sharpe Ratio but only considers downside volatility (losses)',
    learnMore: 'Often preferred over Sharpe Ratio as it ignores upside volatility and focuses on downside risk.',
  },
  correlation: {
    name: 'Correlation',
    definition: 'Measures how closely two assets move together (-1 to 1)',
    learnMore: 'Close to 1: move together. Close to -1: move opposite. 0: independent. Useful for diversification.',
  },
  allocation: {
    name: 'Allocation',
    definition: 'The percentage of portfolio invested in each asset class',
    learnMore: 'Diversification reduces risk. Allocation shows how spread out your investments are.',
  },
  returns: {
    name: 'Returns',
    definition: 'The profit or loss generated by your investments',
    learnMore: 'Can be measured as percentage return or absolute dollars. Often shown daily, monthly, yearly.',
  },
}

export function MetricInfo({ metricKey }: { metricKey: keyof typeof METRIC_DEFINITIONS }) {
  const metric = METRIC_DEFINITIONS[metricKey]
  if (!metric) return null

  return <InfoTooltip label={metric.name} tooltip={metric.definition} learnMore={metric.learnMore} />
}

// Common metric explanations
export function MetricsLegend() {
  return (
    <div className="space-y-2 bg-muted/30 rounded-lg p-4">
      <h3 className="font-semibold text-sm mb-3">Common Metrics</h3>
      <div className="space-y-2 text-xs">
        {Object.entries(METRIC_DEFINITIONS)
          .slice(0, 4)
          .map(([key, def]) => (
            <div key={key} className="flex gap-2">
              <span className="font-medium text-accent min-w-fit">{def.name}</span>
              <span className="text-muted-foreground">{def.definition}</span>
            </div>
          ))}
      </div>
    </div>
  )
}
